config/routes.rb
VatorX::Application.routes.draw do
  get "home/index"

  resources :categories

  resources :competitions

  root :to => "competitions#index"
  get "/list" => "competitions#list", as: :list_competition
  get "/search/:id" => "competitions#search", as: :search_tag
  get "/search/:location" => "competitions#search_location", as: :search_location

end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :competition
  attr_accessible :description, :type
end

app/models/competition.rb
class Competition < ActiveRecord::Base
  attr_accessible :category, :end_date, :start_date, :title, :description, :is_featured, :image, :category_list, :location_list
  acts_as_taggable_on :category, :location
  has_attached_file :image,
  	:styles => {
      :thumb => "360x130#",
  	  :banner => "520x300",
  	  :preview => "100x100"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  # GET /competitions
  # GET /competitions.json
  def index
    @competitions = Competition.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @competitions }
    end
  end

  # GET /competitions/1
  # GET /competitions/1.json
  def show
    @competition = Competition.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @competition }
    end
  end

  # GET /competitions/new
  # GET /competitions/new.json
  def new
    @competition = Competition.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @competition }
    end
  end

  def list
    @competitions = Competition.all
  end

  # GET /competitions/1/edit
  def edit
    @competition = Competition.find(params[:id])
  end

  # POST /competitions
  # POST /competitions.json
  def create
    @competition = Competition.new(params[:competition])

    respond_to do |format|
      if @competition.save
        format.html { redirect_to root_url, notice: 'Competition was successfully created.' }
        format.json { render json: @competition, status: :created, location: @competition }
      else
        format.html { render action: "new" }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /competitions/1
  # PUT /competitions/1.json
  def update
    @competition = Competition.find(params[:id])

    respond_to do |format|
      if @competition.update_attributes(params[:competition])
        format.html { redirect_to edit_competition_path}
        format.js { render 'edit.js.erb'}
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /competitions/1
  # DELETE /competitions/1.json
  def destroy
    @competition = Competition.find(params[:id])
    @competition.destroy

    respond_to do |format|
      format.html { redirect_to list_competition_path }
      format.js { render :layout => false }
      format.json { head :no_content }
    end
  end

  def search
    @tag =  ActsAsTaggableOn::Tag.find(params[:id])
    @competitions = Competition.tagged_with(@tag.name)
  end

  def search_location
    @location =  ActsAsTaggableOn::Tag.find(params[:id])
    @competitions = Competition.tagged_with(@location.name)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :competition %><br />
    <%= f.text_field :competition %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Description</th>
    <th>Type</th>
    <th>Competition</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.description %></td>
    <td><%= category.type %></td>
    <td><%= category.competition %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<%= stylesheet_link_tag params[:controller] %>

<h1 class="title">New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @category.description %>
</p>

<p>
  <b>Type:</b>
  <%= @category.type %>
</p>

<p>
  <b>Competition:</b>
  <%= @category.competition %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/competitions/_edit_form.html.erb
<%= form_for(@competition, :remote => true) do |f| %>
  <div class="competition-form">
    <div class="form-group">
      <% if @competition.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@competition.errors.count, "error") %> prohibited this competition from being saved:
          </h2>

          <ul>
            <% @competition.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control col-sm-4' %>
      </div>
      <div class="form-group">
        <%= f.label :image %>
        <%= image_tag @competition.image.url(:preview), :class => "img-responsive" %>
        <%= f.file_field :image, class: 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :description %><br />
        <%= f.text_area :description, class: 'form-control', :rows => 6  %>
      </div>
      <div class="field" style="position: relative">
        <%= f.label :start_date %><br />
        <%= f.text_field :start_date, class: 'form-control', :required => true%>
      </div>
      <div class="field" style="position: relative">
        <%= f.label :end_date %><br />
        <%= f.text_field :end_date, class: 'form-control', :required => true%>
      </div>
      <div class="field">
        <%= f.label :category %><br />
        <%= f.text_field :category_list, class: 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :location %>
        <%= f.text_field :location_list, class: 'form-control col-sm-4', :required => true%>
      </div>
      <!-- <div class="field">
        <%= f.label :is_featured %>
        <%= f.check_box :is_featured, class: 'form-check-input' %>
      </div> -->
        <center><%= f.submit class: 'btn btn-primary'%></center>
    </div>
  </div>
<% end %>
<div class="actions">
  <center>
    <div class="footer">
      <%= link_to list_competition_path do%>
        <button class="btn btn-seconday footer-button">
          Back to List
        </button>   
      </div>
      <%end%>
  </center>
</div>

app/views/competitions/_form.html.erb
<% content_for :datepicker do %>
  <%= javascript_include_tag "form.js" %>
<% end %>


<%= form_for @competition do |f| %>
  <div class="competition-form">
    <div class="form-group">
      <% if @competition.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@competition.errors.count, "error") %> prohibited this competition from being saved:</h2>

          <ul>
          <% @competition.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control col-sm-4', :required => true%>
      </div>
      <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :image, class: 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :description %><br />
        <%= f.text_area :description, class: 'form-control', :rows => 6, :required => true%>
      </div>
      <div class="field" style="position: relative">
        <%= f.label :start_date %><br />
        <%= f.text_field :start_date, class: 'form-control', :required => true%>
      </div>
      <div class="field" style="position: relative">
        <%= f.label :end_date %><br />
        <%= f.text_field :end_date, class: 'form-control', :required => true%>
      </div>
      <div class="field">
        <%= f.label :category %><br />
        <%= f.text_field :category_list, class: 'form-control', :required => true%>
      </div>
      <div class="field">
        <%= f.label :location %>
        <%= f.text_field :location, class: 'form-control col-sm-4', :required => true%>
      </div>
      <!-- <div class="field">
        <%= f.label :is_featured %>
        <%= f.check_box :is_featured, class: 'form-check-input' %>
      </div> -->
      <div class="actions">
        <center>
          <%= f.submit class: 'btn btn-primary'%>
          <%= submit_tag("Reset", {:type => 'reset', :class => 'btn btn-danger footer-button'}) %>
        </center>
      </div>
    <% end %>
  </div>
</div>
<center>
<div class="footer">
  <%= link_to competitions_path do%>
    <button class="btn btn-seconday footer-button">
      Back to List
    </button>
  <%end%>
</div>  
</center>

app/views/competitions/create.js.erb
var success = '<div class="alert alert-success alert-dismissible show" role="alert" style="width:50%;margin:auto;">Competition successfully updated!</div>'

$(success).insertAfter('.title');

app/views/competitions/destroy.js.erb
$('.delete-competition').bind('ajax:success', function() {  
  $(this).closest('.row').fadeOut();
  console.log("Success")
  $(".alert").remove();
  var success = '<div class="alert alert-success alert-dismissible show" role="alert" style="width:50%;margin-left:auto;margin-right:auto;margin-bottom:2%;">Competition successfully deleted!</div>'
  $(success).insertAfter('.title');
});

app/views/competitions/edit.html.erb
<h1 class="title">Editing competition</h1>

<%= render 'edit_form' %>

app/views/competitions/edit.js.erb
console.log("Success")

$(".alert").remove();

var success = '<div class="alert alert-success alert-dismissible show" role="alert" style="width:50%;margin:auto;">Competition successfully updated!</div>'

$(success).insertAfter('.title');

app/views/competitions/index.html.erb
<%= stylesheet_link_tag params[:controller] %>
  <% content_for :head do %>
<% end %>

<div class="container container-fluid center-field">
  <h2 class="title">Listing Competition</h3>
  <hr size="4" width="25%" noshade>
  <%unless notice.blank?%>
      <div class="alert alert-success alert-dismissible show" 
         role="alert" style="width:89%;margin:auto;">Competition successfully added!
      </div>
  <%end%>
  <%if Competition.blank?%>
    <div class="alert alert-info" role="alert">No records found!</div>
  <%else%>
    <div class="row display-flex">
      <% @competitions.each do |competition| %>
        <div class="col-sm-4">
          <div class="thumbnail">
            <%=link_to competition_path(competition) do%>
                <div class="caption">
                  <%= image_tag competition.image.url(:thumb), :class => "img-responsive" %>
                  <h3 class="competition-title"><%=competition.title%></h3>
                  <p class="competition-description">
                    <%=truncate(strip_tags(competition.description), length: 120, separator: ' ').html_safe%>
                  </p>
                  <p class="competition-category">Category:
                      <%competition.category.each do |category|%>
                        <%= link_to category.name, search_tag_path(category) %>
                      <%end%>
                  </p>
                  <p class="competition-category">Location: 
                    <%competition.location.each do |location|%>
                      <%= link_to location.name, search_location_path(location) %>
                    <%end%>
                  </p>
                  <p class="competition-details"> Competition starts at 
                    <span class="date">
                      <strong>
                        <%=competition.start_date.strftime(' %B %d, %Y, %I:%M %p',)%>
                      </strong>
                    </span> and ends at 
                      <span class="date">
                        <strong>
                          <%=competition.end_date.strftime(' %B %d, %Y, %I:%M %p')%>
                        </strong>
                      </span>
                  </p>
                </div>
            <%end%>
          </div>
        </div>
      <%end%>
    </div>
  <%end%>
  <div id="box" class="footer">
    <%= link_to new_competition_path do%>
      <button class="btn btn-primary footer-button">
        Add Competition
      </button>
    <%end%>
    <%= link_to list_competition_path do%>
      <button class="btn btn-info footer-button">
        Edit Competitions
      </button>   
    <%end%>
  </div>
</div>

app/views/competitions/list.html.erb
<div id="box">
	<h1 class="title">List of Competitions</h1>
  <hr size="4" width="25%" noshade>
    <%unless notice.blank?%>
      <div class="alert alert-success alert-dismissible show" 
        role="alert" style="width:89%;margin:auto;"><%notice%>
      </div>
    <%end%>
		<div class="container constainer-fluid">
      <div class="row">
        <%if Competition.blank?%>
          <div class="alert alert-info" role="alert">No records found!</div>
        <%else%>
            <div class="col-sm-3 edit-item">Competition Title</div>
            <div class="col-sm-3 edit-item">Category</div>
            <div class="col-sm-3 edit-item">Location</div>
            <div class="col-sm-3 edit-item">Action</div>
          </div>
              <% @competitions.each do |c|%>
                <div class="row">
                  <div class="col-sm-3 edit-item"><%=c.title%></div>
                  <div class="col-sm-3 edit-item">
                    <%c.category.each do |category|%>
                      <%= link_to category.name, search_tag_path(category) %>
                    <%end%>
                  </div>
                  <div class="col-sm-3 edit-item">
                    <%c.location.each do |location|%>
                      <%= link_to location.name, search_location_path(location) %>
                    <%end%>
                  </div>
                  <div class="col-sm-1 edit-item">
                    <%= link_to "View", competition_path(c) %>
                  </div>
                  <div class="col-sm-1 edit-item">
                     <%= link_to "Edit", edit_competition_path(c) %>
                  </div>
                  <div class="col-sm-1 edit-item">
                    <%= link_to "Delete", competition_path(c),
                      method: :delete,
                      :remote => true,
                      data: {confirm: 'Are you sure?'},
                      :class => 'delete-competition'
                     %>
                  </div>
                </div>
              <%end%>
        <%end%>
    </div>
    <div class="footer">
      <%= link_to competitions_path do%>
        <button class="btn btn-success">
          Home
        </button>   
      <%end%>
  </div>
</div>

app/views/competitions/new.html.erb
<h1 class="title">New competition</h1>
	<div class="container">
		<%= render 'form' %>
	</div>

app/views/competitions/search.html.erb
<div id="box">
  <h1 class="title">List of Competitions with tag: <span class="category"><%=@tag.name%></span></h1>
  <hr size="4" width="25%" noshade>
    <%unless notice.blank?%>
      <div class="alert alert-success alert-dismissible show" 
        role="alert" style="width:89%;margin:auto;"><%notice%>
      </div>
    <%end%>
    <div class="container constainer-fluid">
      <div class="row">
        <%if Competition.blank?%>
          <div class="alert alert-info" role="alert">No records found!</div>
        <%else%>
            <div class="col-sm-3 edit-item">Competition Title</div>
            <div class="col-sm-3 edit-item">Category</div>
            <div class="col-sm-3 edit-item">Location</div>
            <div class="col-sm-3 edit-item">Action</div>
          </div>
              <% @competitions.each do |c|%>
                <div class="row">
                  <div class="col-sm-3 edit-item"><%=c.title%></div>
                  <div class="col-sm-3 edit-item">
                    <%c.category.each do |category|%>
                      <%= link_to category.name, search_tag_path(category) %>
                    <%end%>
                  </div>
                  <div class="col-sm-3 edit-item">
                    <%c.location.each do |location|%>
                      <%= link_to location.name, search_location_path(location) %>
                    <%end%>
                  </div>
                  <div class="col-sm-1 edit-item">
                    <%= link_to "View", competition_path(c) %>
                  </div>
                  <div class="col-sm-1 edit-item">
                     <%= link_to "Edit", edit_competition_path(c) %>
                  </div>
                  <div class="col-sm-1 edit-item">
                    <%= link_to "Delete", competition_path(c),
                      method: :delete,
                      :remote => true,
                      data: {confirm: 'Are you sure?'},
                      :class => 'delete-competition'
                     %>
                  </div>
                </div>
              <%end%>
        <%end%>
    </div>
    <div class="footer">
      <%= link_to competitions_path do%>
        <button class="btn btn-success">
          Home
        </button>   
      <%end%>
  </div>
</div>

app/views/competitions/show.html.erb
<%= stylesheet_link_tag params[:controller] %>
<% content_for :head do %>
<% end %>

<div class="container-fluid details">
  <center>
    <%= image_tag @competition.image.url(:banner), :class => "img-responsive" %>
  </center>
  <h2 class="title">Competition Details</h2>
  <hr width="25%" noshade>
  <h1 class="competition-title"><%=@competition.title%></h2>
  <hr width="25%" noshade>
  <div class="description-container">
    <h3 class="title">Description</h3>
    <%= simple_format @competition.description%>
  </div>
  <hr width="25%" noshade>
  <div class="category-container">
    <p class="competition-category-title">Category:
      <span class="category">
        <%@competition.category.each do |category|%>
          <%= link_to category.name, search_tag_path(category) %>
        <%end%>
      </span>
    </p>
  </div>
  <hr width="25%" noshade>
  <h3 class="title">Details</h3>
  <div class="detail-container">
    <p>Competition will start at 
      <span class="date">
        <strong>
          <%=@competition.start_date.strftime(' %B %d, %Y')%>
        </strong>
      </span>
      <br />
      and will end at 
      <span class="date">
        <strong>
          <%=@competition.end_date.strftime(' %B %d, %Y')%>
        </strong>
      </span>
    </p>
  </div>
</div>

<center>
  <div class="footer">
    <%= link_to competitions_path do%>
      <button class="btn btn-success">
        Back
      </button>   
    <%end%>
  </div>
</center>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VatorX</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= yield :datepicker %>
  <%= csrf_meta_tags %>
  <% if content_for?(:head) %>
	  <%= yield(:head) %>
	<% end %>
</head>
<body>
<%= yield %>

</body>
</html>